# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile_float_hexa                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: apion <apion@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/02/15 14:36:04 by apion             #+#    #+#              #
#    Updated: 2019/03/12 14:01:22 by apion            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

C_FILES_FLOAT_HEXA := test_float_hexa/001_test_float_hexa_null_a_0_0.c \
	test_float_hexa/002_test_float_hexa_null_neg_a_0_0.c \
	test_float_hexa/003_test_float_hexa_pos_one_a_0_0.c \
	test_float_hexa/004_test_float_hexa_pos_two_a_0_0.c \
	test_float_hexa/005_test_float_hexa_neg_a_0_0.c \
	test_float_hexa/006_test_float_hexa_inf_one_a_0_0.c \
	test_float_hexa/007_test_float_hexa_inf_zero_one_a_0_0.c \
	test_float_hexa/008_test_float_hexa_den_a_0_0.c \
	test_float_hexa/009_test_float_hexa_round_even_top_a_0_0.c \
	test_float_hexa/00_launcher.c \
	test_float_hexa/010_test_float_hexa_round_even_down_a_0_0.c \
	test_float_hexa/011_test_float_hexa_round_even_top_neg_a_0_0.c \
	test_float_hexa/012_test_float_hexa_round_even_down_neg_a_0_0.c \
	test_float_hexa/013_test_float_hexa_dbl_max_a_0_0.c \
	test_float_hexa/014_test_float_hexa_null_a_1_1.c \
	test_float_hexa/015_test_float_hexa_null_neg_a_1_1.c \
	test_float_hexa/016_test_float_hexa_pos_one_a_1_1.c \
	test_float_hexa/017_test_float_hexa_pos_two_a_1_1.c \
	test_float_hexa/018_test_float_hexa_neg_a_1_1.c \
	test_float_hexa/019_test_float_hexa_inf_one_a_1_1.c \
	test_float_hexa/020_test_float_hexa_inf_zero_one_a_1_1.c \
	test_float_hexa/021_test_float_hexa_den_a_1_1.c \
	test_float_hexa/022_test_float_hexa_round_even_top_a_1_1.c \
	test_float_hexa/023_test_float_hexa_round_even_down_a_1_1.c \
	test_float_hexa/024_test_float_hexa_round_even_top_neg_a_1_1.c \
	test_float_hexa/025_test_float_hexa_round_even_down_neg_a_1_1.c \
	test_float_hexa/026_test_float_hexa_dbl_max_a_1_1.c \
	test_float_hexa/027_test_float_hexa_null_a_2_2.c \
	test_float_hexa/028_test_float_hexa_null_neg_a_2_2.c \
	test_float_hexa/029_test_float_hexa_pos_one_a_2_2.c \
	test_float_hexa/030_test_float_hexa_pos_two_a_2_2.c \
	test_float_hexa/031_test_float_hexa_neg_a_2_2.c \
	test_float_hexa/032_test_float_hexa_inf_one_a_2_2.c \
	test_float_hexa/033_test_float_hexa_inf_zero_one_a_2_2.c \
	test_float_hexa/034_test_float_hexa_den_a_2_2.c \
	test_float_hexa/035_test_float_hexa_round_even_top_a_2_2.c \
	test_float_hexa/036_test_float_hexa_round_even_down_a_2_2.c \
	test_float_hexa/037_test_float_hexa_round_even_top_neg_a_2_2.c \
	test_float_hexa/038_test_float_hexa_round_even_down_neg_a_2_2.c \
	test_float_hexa/039_test_float_hexa_dbl_max_a_2_2.c \
	test_float_hexa/040_test_float_hexa_null_a_3_3.c \
	test_float_hexa/041_test_float_hexa_null_neg_a_3_3.c \
	test_float_hexa/042_test_float_hexa_pos_one_a_3_3.c \
	test_float_hexa/043_test_float_hexa_pos_two_a_3_3.c \
	test_float_hexa/044_test_float_hexa_neg_a_3_3.c \
	test_float_hexa/045_test_float_hexa_inf_one_a_3_3.c \
	test_float_hexa/046_test_float_hexa_inf_zero_one_a_3_3.c \
	test_float_hexa/047_test_float_hexa_den_a_3_3.c \
	test_float_hexa/048_test_float_hexa_round_even_top_a_3_3.c \
	test_float_hexa/049_test_float_hexa_round_even_down_a_3_3.c \
	test_float_hexa/050_test_float_hexa_round_even_top_neg_a_3_3.c \
	test_float_hexa/051_test_float_hexa_round_even_down_neg_a_3_3.c \
	test_float_hexa/052_test_float_hexa_dbl_max_a_3_3.c \
	test_float_hexa/053_test_float_hexa_null_a_4_4.c \
	test_float_hexa/054_test_float_hexa_null_neg_a_4_4.c \
	test_float_hexa/055_test_float_hexa_pos_one_a_4_4.c \
	test_float_hexa/056_test_float_hexa_pos_two_a_4_4.c \
	test_float_hexa/057_test_float_hexa_neg_a_4_4.c \
	test_float_hexa/058_test_float_hexa_inf_one_a_4_4.c \
	test_float_hexa/059_test_float_hexa_inf_zero_one_a_4_4.c \
	test_float_hexa/060_test_float_hexa_den_a_4_4.c \
	test_float_hexa/061_test_float_hexa_round_even_top_a_4_4.c \
	test_float_hexa/062_test_float_hexa_round_even_down_a_4_4.c \
	test_float_hexa/063_test_float_hexa_round_even_top_neg_a_4_4.c \
	test_float_hexa/064_test_float_hexa_round_even_down_neg_a_4_4.c \
	test_float_hexa/065_test_float_hexa_dbl_max_a_4_4.c \
	test_float_hexa/066_test_float_hexa_null_a_5_5.c \
	test_float_hexa/067_test_float_hexa_null_neg_a_5_5.c \
	test_float_hexa/068_test_float_hexa_pos_one_a_5_5.c \
	test_float_hexa/069_test_float_hexa_pos_two_a_5_5.c \
	test_float_hexa/070_test_float_hexa_neg_a_5_5.c \
	test_float_hexa/071_test_float_hexa_inf_one_a_5_5.c \
	test_float_hexa/072_test_float_hexa_inf_zero_one_a_5_5.c \
	test_float_hexa/073_test_float_hexa_den_a_5_5.c \
	test_float_hexa/074_test_float_hexa_round_even_top_a_5_5.c \
	test_float_hexa/075_test_float_hexa_round_even_down_a_5_5.c \
	test_float_hexa/076_test_float_hexa_round_even_top_neg_a_5_5.c \
	test_float_hexa/077_test_float_hexa_round_even_down_neg_a_5_5.c \
	test_float_hexa/078_test_float_hexa_dbl_max_a_5_5.c \
	test_float_hexa/079_test_float_hexa_null_a_6_6.c \
	test_float_hexa/080_test_float_hexa_null_neg_a_6_6.c \
	test_float_hexa/081_test_float_hexa_pos_one_a_6_6.c \
	test_float_hexa/082_test_float_hexa_pos_two_a_6_6.c \
	test_float_hexa/083_test_float_hexa_neg_a_6_6.c \
	test_float_hexa/084_test_float_hexa_inf_one_a_6_6.c \
	test_float_hexa/085_test_float_hexa_inf_zero_one_a_6_6.c \
	test_float_hexa/086_test_float_hexa_den_a_6_6.c \
	test_float_hexa/087_test_float_hexa_round_even_top_a_6_6.c \
	test_float_hexa/088_test_float_hexa_round_even_down_a_6_6.c \
	test_float_hexa/089_test_float_hexa_round_even_top_neg_a_6_6.c \
	test_float_hexa/090_test_float_hexa_round_even_down_neg_a_6_6.c \
	test_float_hexa/091_test_float_hexa_dbl_max_a_6_6.c \
	test_float_hexa/092_test_float_hexa_null_a_7_7.c \
	test_float_hexa/093_test_float_hexa_null_neg_a_7_7.c \
	test_float_hexa/094_test_float_hexa_pos_one_a_7_7.c \
	test_float_hexa/095_test_float_hexa_pos_two_a_7_7.c \
	test_float_hexa/096_test_float_hexa_neg_a_7_7.c \
	test_float_hexa/097_test_float_hexa_inf_one_a_7_7.c \
	test_float_hexa/098_test_float_hexa_inf_zero_one_a_7_7.c \
	test_float_hexa/099_test_float_hexa_den_a_7_7.c \
	test_float_hexa/100_test_float_hexa_round_even_top_a_7_7.c \
	test_float_hexa/101_test_float_hexa_round_even_down_a_7_7.c \
	test_float_hexa/102_test_float_hexa_round_even_top_neg_a_7_7.c \
	test_float_hexa/103_test_float_hexa_round_even_down_neg_a_7_7.c \
	test_float_hexa/104_test_float_hexa_dbl_max_a_7_7.c \
	test_float_hexa/105_test_float_hexa_null_a_8_8.c \
	test_float_hexa/106_test_float_hexa_null_neg_a_8_8.c \
	test_float_hexa/107_test_float_hexa_pos_one_a_8_8.c \
	test_float_hexa/108_test_float_hexa_pos_two_a_8_8.c \
	test_float_hexa/109_test_float_hexa_neg_a_8_8.c \
	test_float_hexa/110_test_float_hexa_inf_one_a_8_8.c \
	test_float_hexa/111_test_float_hexa_inf_zero_one_a_8_8.c \
	test_float_hexa/112_test_float_hexa_den_a_8_8.c \
	test_float_hexa/113_test_float_hexa_round_even_top_a_8_8.c \
	test_float_hexa/114_test_float_hexa_round_even_down_a_8_8.c \
	test_float_hexa/115_test_float_hexa_round_even_top_neg_a_8_8.c \
	test_float_hexa/116_test_float_hexa_round_even_down_neg_a_8_8.c \
	test_float_hexa/117_test_float_hexa_dbl_max_a_8_8.c \
	test_float_hexa/118_test_float_hexa_null_a_9_9.c \
	test_float_hexa/119_test_float_hexa_null_neg_a_9_9.c \
	test_float_hexa/120_test_float_hexa_pos_one_a_9_9.c \
	test_float_hexa/121_test_float_hexa_pos_two_a_9_9.c \
	test_float_hexa/122_test_float_hexa_neg_a_9_9.c \
	test_float_hexa/123_test_float_hexa_inf_one_a_9_9.c \
	test_float_hexa/124_test_float_hexa_inf_zero_one_a_9_9.c \
	test_float_hexa/125_test_float_hexa_den_a_9_9.c \
	test_float_hexa/126_test_float_hexa_round_even_top_a_9_9.c \
	test_float_hexa/127_test_float_hexa_round_even_down_a_9_9.c \
	test_float_hexa/128_test_float_hexa_round_even_top_neg_a_9_9.c \
	test_float_hexa/129_test_float_hexa_round_even_down_neg_a_9_9.c \
	test_float_hexa/130_test_float_hexa_dbl_max_a_9_9.c \
	test_float_hexa/131_test_float_hexa_null_a_10_10.c \
	test_float_hexa/132_test_float_hexa_null_neg_a_10_10.c \
	test_float_hexa/133_test_float_hexa_pos_one_a_10_10.c \
	test_float_hexa/134_test_float_hexa_pos_two_a_10_10.c \
	test_float_hexa/135_test_float_hexa_neg_a_10_10.c \
	test_float_hexa/136_test_float_hexa_inf_one_a_10_10.c \
	test_float_hexa/137_test_float_hexa_inf_zero_one_a_10_10.c \
	test_float_hexa/138_test_float_hexa_den_a_10_10.c \
	test_float_hexa/139_test_float_hexa_round_even_top_a_10_10.c \
	test_float_hexa/140_test_float_hexa_round_even_down_a_10_10.c \
	test_float_hexa/141_test_float_hexa_round_even_top_neg_a_10_10.c \
	test_float_hexa/142_test_float_hexa_round_even_down_neg_a_10_10.c \
	test_float_hexa/143_test_float_hexa_dbl_max_a_10_10.c \
	test_float_hexa/144_test_float_hexa_null_a_11_11.c \
	test_float_hexa/145_test_float_hexa_null_neg_a_11_11.c \
	test_float_hexa/146_test_float_hexa_pos_one_a_11_11.c \
	test_float_hexa/147_test_float_hexa_pos_two_a_11_11.c \
	test_float_hexa/148_test_float_hexa_neg_a_11_11.c \
	test_float_hexa/149_test_float_hexa_inf_one_a_11_11.c \
	test_float_hexa/150_test_float_hexa_inf_zero_one_a_11_11.c \
	test_float_hexa/151_test_float_hexa_den_a_11_11.c \
	test_float_hexa/152_test_float_hexa_round_even_top_a_11_11.c \
	test_float_hexa/153_test_float_hexa_round_even_down_a_11_11.c \
	test_float_hexa/154_test_float_hexa_round_even_top_neg_a_11_11.c \
	test_float_hexa/155_test_float_hexa_round_even_down_neg_a_11_11.c \
	test_float_hexa/156_test_float_hexa_dbl_max_a_11_11.c \
	test_float_hexa/157_test_float_hexa_null_a_12_12.c \
	test_float_hexa/158_test_float_hexa_null_neg_a_12_12.c \
	test_float_hexa/159_test_float_hexa_pos_one_a_12_12.c \
	test_float_hexa/160_test_float_hexa_pos_two_a_12_12.c \
	test_float_hexa/161_test_float_hexa_neg_a_12_12.c \
	test_float_hexa/162_test_float_hexa_inf_one_a_12_12.c \
	test_float_hexa/163_test_float_hexa_inf_zero_one_a_12_12.c \
	test_float_hexa/164_test_float_hexa_den_a_12_12.c \
	test_float_hexa/165_test_float_hexa_round_even_top_a_12_12.c \
	test_float_hexa/166_test_float_hexa_round_even_down_a_12_12.c \
	test_float_hexa/167_test_float_hexa_round_even_top_neg_a_12_12.c \
	test_float_hexa/168_test_float_hexa_round_even_down_neg_a_12_12.c \
	test_float_hexa/169_test_float_hexa_dbl_max_a_12_12.c \
	test_float_hexa/170_test_float_hexa_null_a_13_13.c \
	test_float_hexa/171_test_float_hexa_null_neg_a_13_13.c \
	test_float_hexa/172_test_float_hexa_pos_one_a_13_13.c \
	test_float_hexa/173_test_float_hexa_pos_two_a_13_13.c \
	test_float_hexa/174_test_float_hexa_neg_a_13_13.c \
	test_float_hexa/175_test_float_hexa_inf_one_a_13_13.c \
	test_float_hexa/176_test_float_hexa_inf_zero_one_a_13_13.c \
	test_float_hexa/177_test_float_hexa_den_a_13_13.c \
	test_float_hexa/178_test_float_hexa_round_even_top_a_13_13.c \
	test_float_hexa/179_test_float_hexa_round_even_down_a_13_13.c \
	test_float_hexa/180_test_float_hexa_round_even_top_neg_a_13_13.c \
	test_float_hexa/181_test_float_hexa_round_even_down_neg_a_13_13.c \
	test_float_hexa/182_test_float_hexa_dbl_max_a_13_13.c \
	test_float_hexa/183_test_float_hexa_null_a_14_14.c \
	test_float_hexa/184_test_float_hexa_null_neg_a_14_14.c \
	test_float_hexa/185_test_float_hexa_pos_one_a_14_14.c \
	test_float_hexa/186_test_float_hexa_pos_two_a_14_14.c \
	test_float_hexa/187_test_float_hexa_neg_a_14_14.c \
	test_float_hexa/188_test_float_hexa_inf_one_a_14_14.c \
	test_float_hexa/189_test_float_hexa_inf_zero_one_a_14_14.c \
	test_float_hexa/190_test_float_hexa_den_a_14_14.c \
	test_float_hexa/191_test_float_hexa_round_even_top_a_14_14.c \
	test_float_hexa/192_test_float_hexa_round_even_down_a_14_14.c \
	test_float_hexa/193_test_float_hexa_round_even_top_neg_a_14_14.c \
	test_float_hexa/194_test_float_hexa_round_even_down_neg_a_14_14.c \
	test_float_hexa/195_test_float_hexa_dbl_max_a_14_14.c \
	test_float_hexa/196_test_float_hexa_null_a_15_15.c \
	test_float_hexa/197_test_float_hexa_null_neg_a_15_15.c \
	test_float_hexa/198_test_float_hexa_pos_one_a_15_15.c \
	test_float_hexa/199_test_float_hexa_pos_two_a_15_15.c \
	test_float_hexa/200_test_float_hexa_neg_a_15_15.c \
	test_float_hexa/201_test_float_hexa_inf_one_a_15_15.c \
	test_float_hexa/202_test_float_hexa_inf_zero_one_a_15_15.c \
	test_float_hexa/203_test_float_hexa_den_a_15_15.c \
	test_float_hexa/204_test_float_hexa_round_even_top_a_15_15.c \
	test_float_hexa/205_test_float_hexa_round_even_down_a_15_15.c \
	test_float_hexa/206_test_float_hexa_round_even_top_neg_a_15_15.c \
	test_float_hexa/207_test_float_hexa_round_even_down_neg_a_15_15.c \
	test_float_hexa/208_test_float_hexa_dbl_max_a_15_15.c \
	test_float_hexa/209_test_float_hexa_null_a_16_16.c \
	test_float_hexa/210_test_float_hexa_null_neg_a_16_16.c \
	test_float_hexa/211_test_float_hexa_pos_one_a_16_16.c \
	test_float_hexa/212_test_float_hexa_pos_two_a_16_16.c \
	test_float_hexa/213_test_float_hexa_neg_a_16_16.c \
	test_float_hexa/214_test_float_hexa_inf_one_a_16_16.c \
	test_float_hexa/215_test_float_hexa_inf_zero_one_a_16_16.c \
	test_float_hexa/216_test_float_hexa_den_a_16_16.c \
	test_float_hexa/217_test_float_hexa_round_even_top_a_16_16.c \
	test_float_hexa/218_test_float_hexa_round_even_down_a_16_16.c \
	test_float_hexa/219_test_float_hexa_round_even_top_neg_a_16_16.c \
	test_float_hexa/220_test_float_hexa_round_even_down_neg_a_16_16.c \
	test_float_hexa/221_test_float_hexa_dbl_max_a_16_16.c \
	test_float_hexa/222_test_float_hexa_null_A_0_0.c \
	test_float_hexa/223_test_float_hexa_null_neg_A_0_0.c \
	test_float_hexa/224_test_float_hexa_pos_one_A_0_0.c \
	test_float_hexa/225_test_float_hexa_pos_two_A_0_0.c \
	test_float_hexa/226_test_float_hexa_neg_A_0_0.c \
	test_float_hexa/227_test_float_hexa_inf_one_A_0_0.c \
	test_float_hexa/228_test_float_hexa_inf_zero_one_A_0_0.c \
	test_float_hexa/229_test_float_hexa_den_A_0_0.c \
	test_float_hexa/230_test_float_hexa_round_even_top_A_0_0.c \
	test_float_hexa/231_test_float_hexa_round_even_down_A_0_0.c \
	test_float_hexa/232_test_float_hexa_round_even_top_neg_A_0_0.c \
	test_float_hexa/233_test_float_hexa_round_even_down_neg_A_0_0.c \
	test_float_hexa/234_test_float_hexa_dbl_max_A_0_0.c \
	test_float_hexa/235_test_float_hexa_null_A_1_1.c \
	test_float_hexa/236_test_float_hexa_null_neg_A_1_1.c \
	test_float_hexa/237_test_float_hexa_pos_one_A_1_1.c \
	test_float_hexa/238_test_float_hexa_pos_two_A_1_1.c \
	test_float_hexa/239_test_float_hexa_neg_A_1_1.c \
	test_float_hexa/240_test_float_hexa_inf_one_A_1_1.c \
	test_float_hexa/241_test_float_hexa_inf_zero_one_A_1_1.c \
	test_float_hexa/242_test_float_hexa_den_A_1_1.c \
	test_float_hexa/243_test_float_hexa_round_even_top_A_1_1.c \
	test_float_hexa/244_test_float_hexa_round_even_down_A_1_1.c \
	test_float_hexa/245_test_float_hexa_round_even_top_neg_A_1_1.c \
	test_float_hexa/246_test_float_hexa_round_even_down_neg_A_1_1.c \
	test_float_hexa/247_test_float_hexa_dbl_max_A_1_1.c \
	test_float_hexa/248_test_float_hexa_null_A_2_2.c \
	test_float_hexa/249_test_float_hexa_null_neg_A_2_2.c \
	test_float_hexa/250_test_float_hexa_pos_one_A_2_2.c \
	test_float_hexa/251_test_float_hexa_pos_two_A_2_2.c \
	test_float_hexa/252_test_float_hexa_neg_A_2_2.c \
	test_float_hexa/253_test_float_hexa_inf_one_A_2_2.c \
	test_float_hexa/254_test_float_hexa_inf_zero_one_A_2_2.c \
	test_float_hexa/255_test_float_hexa_den_A_2_2.c \
	test_float_hexa/256_test_float_hexa_round_even_top_A_2_2.c \
	test_float_hexa/257_test_float_hexa_round_even_down_A_2_2.c \
	test_float_hexa/258_test_float_hexa_round_even_top_neg_A_2_2.c \
	test_float_hexa/259_test_float_hexa_round_even_down_neg_A_2_2.c \
	test_float_hexa/260_test_float_hexa_dbl_max_A_2_2.c \
	test_float_hexa/261_test_float_hexa_null_A_3_3.c \
	test_float_hexa/262_test_float_hexa_null_neg_A_3_3.c \
	test_float_hexa/263_test_float_hexa_pos_one_A_3_3.c \
	test_float_hexa/264_test_float_hexa_pos_two_A_3_3.c \
	test_float_hexa/265_test_float_hexa_neg_A_3_3.c \
	test_float_hexa/266_test_float_hexa_inf_one_A_3_3.c \
	test_float_hexa/267_test_float_hexa_inf_zero_one_A_3_3.c \
	test_float_hexa/268_test_float_hexa_den_A_3_3.c \
	test_float_hexa/269_test_float_hexa_round_even_top_A_3_3.c \
	test_float_hexa/270_test_float_hexa_round_even_down_A_3_3.c \
	test_float_hexa/271_test_float_hexa_round_even_top_neg_A_3_3.c \
	test_float_hexa/272_test_float_hexa_round_even_down_neg_A_3_3.c \
	test_float_hexa/273_test_float_hexa_dbl_max_A_3_3.c \
	test_float_hexa/274_test_float_hexa_null_A_4_4.c \
	test_float_hexa/275_test_float_hexa_null_neg_A_4_4.c \
	test_float_hexa/276_test_float_hexa_pos_one_A_4_4.c \
	test_float_hexa/277_test_float_hexa_pos_two_A_4_4.c \
	test_float_hexa/278_test_float_hexa_neg_A_4_4.c \
	test_float_hexa/279_test_float_hexa_inf_one_A_4_4.c \
	test_float_hexa/280_test_float_hexa_inf_zero_one_A_4_4.c \
	test_float_hexa/281_test_float_hexa_den_A_4_4.c \
	test_float_hexa/282_test_float_hexa_round_even_top_A_4_4.c \
	test_float_hexa/283_test_float_hexa_round_even_down_A_4_4.c \
	test_float_hexa/284_test_float_hexa_round_even_top_neg_A_4_4.c \
	test_float_hexa/285_test_float_hexa_round_even_down_neg_A_4_4.c \
	test_float_hexa/286_test_float_hexa_dbl_max_A_4_4.c \
	test_float_hexa/287_test_float_hexa_null_A_5_5.c \
	test_float_hexa/288_test_float_hexa_null_neg_A_5_5.c \
	test_float_hexa/289_test_float_hexa_pos_one_A_5_5.c \
	test_float_hexa/290_test_float_hexa_pos_two_A_5_5.c \
	test_float_hexa/291_test_float_hexa_neg_A_5_5.c \
	test_float_hexa/292_test_float_hexa_inf_one_A_5_5.c \
	test_float_hexa/293_test_float_hexa_inf_zero_one_A_5_5.c \
	test_float_hexa/294_test_float_hexa_den_A_5_5.c \
	test_float_hexa/295_test_float_hexa_round_even_top_A_5_5.c \
	test_float_hexa/296_test_float_hexa_round_even_down_A_5_5.c \
	test_float_hexa/297_test_float_hexa_round_even_top_neg_A_5_5.c \
	test_float_hexa/298_test_float_hexa_round_even_down_neg_A_5_5.c \
	test_float_hexa/299_test_float_hexa_dbl_max_A_5_5.c \
	test_float_hexa/300_test_float_hexa_null_A_6_6.c \
	test_float_hexa/301_test_float_hexa_null_neg_A_6_6.c \
	test_float_hexa/302_test_float_hexa_pos_one_A_6_6.c \
	test_float_hexa/303_test_float_hexa_pos_two_A_6_6.c \
	test_float_hexa/304_test_float_hexa_neg_A_6_6.c \
	test_float_hexa/305_test_float_hexa_inf_one_A_6_6.c \
	test_float_hexa/306_test_float_hexa_inf_zero_one_A_6_6.c \
	test_float_hexa/307_test_float_hexa_den_A_6_6.c \
	test_float_hexa/308_test_float_hexa_round_even_top_A_6_6.c \
	test_float_hexa/309_test_float_hexa_round_even_down_A_6_6.c \
	test_float_hexa/310_test_float_hexa_round_even_top_neg_A_6_6.c \
	test_float_hexa/311_test_float_hexa_round_even_down_neg_A_6_6.c \
	test_float_hexa/312_test_float_hexa_dbl_max_A_6_6.c \
	test_float_hexa/313_test_float_hexa_null_A_7_7.c \
	test_float_hexa/314_test_float_hexa_null_neg_A_7_7.c \
	test_float_hexa/315_test_float_hexa_pos_one_A_7_7.c \
	test_float_hexa/316_test_float_hexa_pos_two_A_7_7.c \
	test_float_hexa/317_test_float_hexa_neg_A_7_7.c \
	test_float_hexa/318_test_float_hexa_inf_one_A_7_7.c \
	test_float_hexa/319_test_float_hexa_inf_zero_one_A_7_7.c \
	test_float_hexa/320_test_float_hexa_den_A_7_7.c \
	test_float_hexa/321_test_float_hexa_round_even_top_A_7_7.c \
	test_float_hexa/322_test_float_hexa_round_even_down_A_7_7.c \
	test_float_hexa/323_test_float_hexa_round_even_top_neg_A_7_7.c \
	test_float_hexa/324_test_float_hexa_round_even_down_neg_A_7_7.c \
	test_float_hexa/325_test_float_hexa_dbl_max_A_7_7.c \
	test_float_hexa/326_test_float_hexa_null_A_8_8.c \
	test_float_hexa/327_test_float_hexa_null_neg_A_8_8.c \
	test_float_hexa/328_test_float_hexa_pos_one_A_8_8.c \
	test_float_hexa/329_test_float_hexa_pos_two_A_8_8.c \
	test_float_hexa/330_test_float_hexa_neg_A_8_8.c \
	test_float_hexa/331_test_float_hexa_inf_one_A_8_8.c \
	test_float_hexa/332_test_float_hexa_inf_zero_one_A_8_8.c \
	test_float_hexa/333_test_float_hexa_den_A_8_8.c \
	test_float_hexa/334_test_float_hexa_round_even_top_A_8_8.c \
	test_float_hexa/335_test_float_hexa_round_even_down_A_8_8.c \
	test_float_hexa/336_test_float_hexa_round_even_top_neg_A_8_8.c \
	test_float_hexa/337_test_float_hexa_round_even_down_neg_A_8_8.c \
	test_float_hexa/338_test_float_hexa_dbl_max_A_8_8.c \
	test_float_hexa/339_test_float_hexa_null_A_9_9.c \
	test_float_hexa/340_test_float_hexa_null_neg_A_9_9.c \
	test_float_hexa/341_test_float_hexa_pos_one_A_9_9.c \
	test_float_hexa/342_test_float_hexa_pos_two_A_9_9.c \
	test_float_hexa/343_test_float_hexa_neg_A_9_9.c \
	test_float_hexa/344_test_float_hexa_inf_one_A_9_9.c \
	test_float_hexa/345_test_float_hexa_inf_zero_one_A_9_9.c \
	test_float_hexa/346_test_float_hexa_den_A_9_9.c \
	test_float_hexa/347_test_float_hexa_round_even_top_A_9_9.c \
	test_float_hexa/348_test_float_hexa_round_even_down_A_9_9.c \
	test_float_hexa/349_test_float_hexa_round_even_top_neg_A_9_9.c \
	test_float_hexa/350_test_float_hexa_round_even_down_neg_A_9_9.c \
	test_float_hexa/351_test_float_hexa_dbl_max_A_9_9.c \
	test_float_hexa/352_test_float_hexa_null_A_10_10.c \
	test_float_hexa/353_test_float_hexa_null_neg_A_10_10.c \
	test_float_hexa/354_test_float_hexa_pos_one_A_10_10.c \
	test_float_hexa/355_test_float_hexa_pos_two_A_10_10.c \
	test_float_hexa/356_test_float_hexa_neg_A_10_10.c \
	test_float_hexa/357_test_float_hexa_inf_one_A_10_10.c \
	test_float_hexa/358_test_float_hexa_inf_zero_one_A_10_10.c \
	test_float_hexa/359_test_float_hexa_den_A_10_10.c \
	test_float_hexa/360_test_float_hexa_round_even_top_A_10_10.c \
	test_float_hexa/361_test_float_hexa_round_even_down_A_10_10.c \
	test_float_hexa/362_test_float_hexa_round_even_top_neg_A_10_10.c \
	test_float_hexa/363_test_float_hexa_round_even_down_neg_A_10_10.c \
	test_float_hexa/364_test_float_hexa_dbl_max_A_10_10.c \
	test_float_hexa/365_test_float_hexa_null_A_11_11.c \
	test_float_hexa/366_test_float_hexa_null_neg_A_11_11.c \
	test_float_hexa/367_test_float_hexa_pos_one_A_11_11.c \
	test_float_hexa/368_test_float_hexa_pos_two_A_11_11.c \
	test_float_hexa/369_test_float_hexa_neg_A_11_11.c \
	test_float_hexa/370_test_float_hexa_inf_one_A_11_11.c \
	test_float_hexa/371_test_float_hexa_inf_zero_one_A_11_11.c \
	test_float_hexa/372_test_float_hexa_den_A_11_11.c \
	test_float_hexa/373_test_float_hexa_round_even_top_A_11_11.c \
	test_float_hexa/374_test_float_hexa_round_even_down_A_11_11.c \
	test_float_hexa/375_test_float_hexa_round_even_top_neg_A_11_11.c \
	test_float_hexa/376_test_float_hexa_round_even_down_neg_A_11_11.c \
	test_float_hexa/377_test_float_hexa_dbl_max_A_11_11.c \
	test_float_hexa/378_test_float_hexa_null_A_12_12.c \
	test_float_hexa/379_test_float_hexa_null_neg_A_12_12.c \
	test_float_hexa/380_test_float_hexa_pos_one_A_12_12.c \
	test_float_hexa/381_test_float_hexa_pos_two_A_12_12.c \
	test_float_hexa/382_test_float_hexa_neg_A_12_12.c \
	test_float_hexa/383_test_float_hexa_inf_one_A_12_12.c \
	test_float_hexa/384_test_float_hexa_inf_zero_one_A_12_12.c \
	test_float_hexa/385_test_float_hexa_den_A_12_12.c \
	test_float_hexa/386_test_float_hexa_round_even_top_A_12_12.c \
	test_float_hexa/387_test_float_hexa_round_even_down_A_12_12.c \
	test_float_hexa/388_test_float_hexa_round_even_top_neg_A_12_12.c \
	test_float_hexa/389_test_float_hexa_round_even_down_neg_A_12_12.c \
	test_float_hexa/390_test_float_hexa_dbl_max_A_12_12.c \
	test_float_hexa/391_test_float_hexa_null_A_13_13.c \
	test_float_hexa/392_test_float_hexa_null_neg_A_13_13.c \
	test_float_hexa/393_test_float_hexa_pos_one_A_13_13.c \
	test_float_hexa/394_test_float_hexa_pos_two_A_13_13.c \
	test_float_hexa/395_test_float_hexa_neg_A_13_13.c \
	test_float_hexa/396_test_float_hexa_inf_one_A_13_13.c \
	test_float_hexa/397_test_float_hexa_inf_zero_one_A_13_13.c \
	test_float_hexa/398_test_float_hexa_den_A_13_13.c \
	test_float_hexa/399_test_float_hexa_round_even_top_A_13_13.c \
	test_float_hexa/400_test_float_hexa_round_even_down_A_13_13.c \
	test_float_hexa/401_test_float_hexa_round_even_top_neg_A_13_13.c \
	test_float_hexa/402_test_float_hexa_round_even_down_neg_A_13_13.c \
	test_float_hexa/403_test_float_hexa_dbl_max_A_13_13.c \
	test_float_hexa/404_test_float_hexa_null_A_14_14.c \
	test_float_hexa/405_test_float_hexa_null_neg_A_14_14.c \
	test_float_hexa/406_test_float_hexa_pos_one_A_14_14.c \
	test_float_hexa/407_test_float_hexa_pos_two_A_14_14.c \
	test_float_hexa/408_test_float_hexa_neg_A_14_14.c \
	test_float_hexa/409_test_float_hexa_inf_one_A_14_14.c \
	test_float_hexa/410_test_float_hexa_inf_zero_one_A_14_14.c \
	test_float_hexa/411_test_float_hexa_den_A_14_14.c \
	test_float_hexa/412_test_float_hexa_round_even_top_A_14_14.c \
	test_float_hexa/413_test_float_hexa_round_even_down_A_14_14.c \
	test_float_hexa/414_test_float_hexa_round_even_top_neg_A_14_14.c \
	test_float_hexa/415_test_float_hexa_round_even_down_neg_A_14_14.c \
	test_float_hexa/416_test_float_hexa_dbl_max_A_14_14.c \
	test_float_hexa/417_test_float_hexa_null_A_15_15.c \
	test_float_hexa/418_test_float_hexa_null_neg_A_15_15.c \
	test_float_hexa/419_test_float_hexa_pos_one_A_15_15.c \
	test_float_hexa/420_test_float_hexa_pos_two_A_15_15.c \
	test_float_hexa/421_test_float_hexa_neg_A_15_15.c \
	test_float_hexa/422_test_float_hexa_inf_one_A_15_15.c \
	test_float_hexa/423_test_float_hexa_inf_zero_one_A_15_15.c \
	test_float_hexa/424_test_float_hexa_den_A_15_15.c \
	test_float_hexa/425_test_float_hexa_round_even_top_A_15_15.c \
	test_float_hexa/426_test_float_hexa_round_even_down_A_15_15.c \
	test_float_hexa/427_test_float_hexa_round_even_top_neg_A_15_15.c \
	test_float_hexa/428_test_float_hexa_round_even_down_neg_A_15_15.c \
	test_float_hexa/429_test_float_hexa_dbl_max_A_15_15.c \
	test_float_hexa/430_test_float_hexa_null_A_16_16.c \
	test_float_hexa/431_test_float_hexa_null_neg_A_16_16.c \
	test_float_hexa/432_test_float_hexa_pos_one_A_16_16.c \
	test_float_hexa/433_test_float_hexa_pos_two_A_16_16.c \
	test_float_hexa/434_test_float_hexa_neg_A_16_16.c \
	test_float_hexa/435_test_float_hexa_inf_one_A_16_16.c \
	test_float_hexa/436_test_float_hexa_inf_zero_one_A_16_16.c \
	test_float_hexa/437_test_float_hexa_den_A_16_16.c \
	test_float_hexa/438_test_float_hexa_round_even_top_A_16_16.c \
	test_float_hexa/439_test_float_hexa_round_even_down_A_16_16.c \
	test_float_hexa/440_test_float_hexa_round_even_top_neg_A_16_16.c \
	test_float_hexa/441_test_float_hexa_round_even_down_neg_A_16_16.c \
	test_float_hexa/442_test_float_hexa_dbl_max_A_16_16.c
