# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile_float                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: apion <apion@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/02/15 14:36:04 by apion             #+#    #+#              #
#    Updated: 2019/02/15 14:38:35 by apion            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

C_FILES_FLOAT := test_float_hexa/001_test_float_hexa_null_a_0_0.c \
					test_float_hexa/002_test_float_hexa_null_neg_a_0_0.c \
					test_float_hexa/003_test_float_hexa_pos_one_a_0_0.c \
					test_float_hexa/004_test_float_hexa_pos_two_a_0_0.c \
					test_float_hexa/005_test_float_hexa_neg_a_0_0.c \
					test_float_hexa/006_test_float_hexa_inf_one_a_0_0.c \
					test_float_hexa/007_test_float_hexa_inf_zero_one_a_0_0.c \
					test_float_hexa/008_test_float_hexa_den_a_0_0.c \
					test_float_hexa/009_test_float_hexa_round_even_top_a_0_0.c \
					test_float_hexa/00_launcher.c \
					test_float_hexa/010_test_float_hexa_round_even_down_a_0_0.c \
					test_float_hexa/011_test_float_hexa_round_even_top_neg_a_0_0.c \
					test_float_hexa/012_test_float_hexa_round_even_down_neg_a_0_0.c \
					test_float_hexa/013_test_float_hexa_null_a_1_1.c \
					test_float_hexa/014_test_float_hexa_null_neg_a_1_1.c \
					test_float_hexa/015_test_float_hexa_pos_one_a_1_1.c \
					test_float_hexa/016_test_float_hexa_pos_two_a_1_1.c \
					test_float_hexa/017_test_float_hexa_neg_a_1_1.c \
					test_float_hexa/018_test_float_hexa_inf_one_a_1_1.c \
					test_float_hexa/019_test_float_hexa_inf_zero_one_a_1_1.c \
					test_float_hexa/020_test_float_hexa_den_a_1_1.c \
					test_float_hexa/021_test_float_hexa_round_even_top_a_1_1.c \
					test_float_hexa/022_test_float_hexa_round_even_down_a_1_1.c \
					test_float_hexa/023_test_float_hexa_round_even_top_neg_a_1_1.c \
					test_float_hexa/024_test_float_hexa_round_even_down_neg_a_1_1.c \
					test_float_hexa/025_test_float_hexa_null_a_2_2.c \
					test_float_hexa/026_test_float_hexa_null_neg_a_2_2.c \
					test_float_hexa/027_test_float_hexa_pos_one_a_2_2.c \
					test_float_hexa/028_test_float_hexa_pos_two_a_2_2.c \
					test_float_hexa/029_test_float_hexa_neg_a_2_2.c \
					test_float_hexa/030_test_float_hexa_inf_one_a_2_2.c \
					test_float_hexa/031_test_float_hexa_inf_zero_one_a_2_2.c \
					test_float_hexa/032_test_float_hexa_den_a_2_2.c \
					test_float_hexa/033_test_float_hexa_round_even_top_a_2_2.c \
					test_float_hexa/034_test_float_hexa_round_even_down_a_2_2.c \
					test_float_hexa/035_test_float_hexa_round_even_top_neg_a_2_2.c \
					test_float_hexa/036_test_float_hexa_round_even_down_neg_a_2_2.c \
					test_float_hexa/037_test_float_hexa_null_a_3_3.c \
					test_float_hexa/038_test_float_hexa_null_neg_a_3_3.c \
					test_float_hexa/039_test_float_hexa_pos_one_a_3_3.c \
					test_float_hexa/040_test_float_hexa_pos_two_a_3_3.c \
					test_float_hexa/041_test_float_hexa_neg_a_3_3.c \
					test_float_hexa/042_test_float_hexa_inf_one_a_3_3.c \
					test_float_hexa/043_test_float_hexa_inf_zero_one_a_3_3.c \
					test_float_hexa/044_test_float_hexa_den_a_3_3.c \
					test_float_hexa/045_test_float_hexa_round_even_top_a_3_3.c \
					test_float_hexa/046_test_float_hexa_round_even_down_a_3_3.c \
					test_float_hexa/047_test_float_hexa_round_even_top_neg_a_3_3.c \
					test_float_hexa/048_test_float_hexa_round_even_down_neg_a_3_3.c \
					test_float_hexa/049_test_float_hexa_null_a_4_4.c \
					test_float_hexa/050_test_float_hexa_null_neg_a_4_4.c \
					test_float_hexa/051_test_float_hexa_pos_one_a_4_4.c \
					test_float_hexa/052_test_float_hexa_pos_two_a_4_4.c \
					test_float_hexa/053_test_float_hexa_neg_a_4_4.c \
					test_float_hexa/054_test_float_hexa_inf_one_a_4_4.c \
					test_float_hexa/055_test_float_hexa_inf_zero_one_a_4_4.c \
					test_float_hexa/056_test_float_hexa_den_a_4_4.c \
					test_float_hexa/057_test_float_hexa_round_even_top_a_4_4.c \
					test_float_hexa/058_test_float_hexa_round_even_down_a_4_4.c \
					test_float_hexa/059_test_float_hexa_round_even_top_neg_a_4_4.c \
					test_float_hexa/060_test_float_hexa_round_even_down_neg_a_4_4.c \
					test_float_hexa/061_test_float_hexa_null_a_5_5.c \
					test_float_hexa/062_test_float_hexa_null_neg_a_5_5.c \
					test_float_hexa/063_test_float_hexa_pos_one_a_5_5.c \
					test_float_hexa/064_test_float_hexa_pos_two_a_5_5.c \
					test_float_hexa/065_test_float_hexa_neg_a_5_5.c \
					test_float_hexa/066_test_float_hexa_inf_one_a_5_5.c \
					test_float_hexa/067_test_float_hexa_inf_zero_one_a_5_5.c \
					test_float_hexa/068_test_float_hexa_den_a_5_5.c \
					test_float_hexa/069_test_float_hexa_round_even_top_a_5_5.c \
					test_float_hexa/070_test_float_hexa_round_even_down_a_5_5.c \
					test_float_hexa/071_test_float_hexa_round_even_top_neg_a_5_5.c \
					test_float_hexa/072_test_float_hexa_round_even_down_neg_a_5_5.c \
					test_float_hexa/073_test_float_hexa_null_A_0_0.c \
					test_float_hexa/074_test_float_hexa_null_neg_A_0_0.c \
					test_float_hexa/075_test_float_hexa_pos_one_A_0_0.c \
					test_float_hexa/076_test_float_hexa_pos_two_A_0_0.c \
					test_float_hexa/077_test_float_hexa_neg_A_0_0.c \
					test_float_hexa/078_test_float_hexa_inf_one_A_0_0.c \
					test_float_hexa/079_test_float_hexa_inf_zero_one_A_0_0.c \
					test_float_hexa/080_test_float_hexa_den_A_0_0.c \
					test_float_hexa/081_test_float_hexa_round_even_top_A_0_0.c \
					test_float_hexa/082_test_float_hexa_round_even_down_A_0_0.c \
					test_float_hexa/083_test_float_hexa_round_even_top_neg_A_0_0.c \
					test_float_hexa/084_test_float_hexa_round_even_down_neg_A_0_0.c \
					test_float_hexa/085_test_float_hexa_null_A_1_1.c \
					test_float_hexa/086_test_float_hexa_null_neg_A_1_1.c \
					test_float_hexa/087_test_float_hexa_pos_one_A_1_1.c \
					test_float_hexa/088_test_float_hexa_pos_two_A_1_1.c \
					test_float_hexa/089_test_float_hexa_neg_A_1_1.c \
					test_float_hexa/090_test_float_hexa_inf_one_A_1_1.c \
					test_float_hexa/091_test_float_hexa_inf_zero_one_A_1_1.c \
					test_float_hexa/092_test_float_hexa_den_A_1_1.c \
					test_float_hexa/093_test_float_hexa_round_even_top_A_1_1.c \
					test_float_hexa/094_test_float_hexa_round_even_down_A_1_1.c \
					test_float_hexa/095_test_float_hexa_round_even_top_neg_A_1_1.c \
					test_float_hexa/096_test_float_hexa_round_even_down_neg_A_1_1.c \
					test_float_hexa/097_test_float_hexa_null_A_2_2.c \
					test_float_hexa/098_test_float_hexa_null_neg_A_2_2.c \
					test_float_hexa/099_test_float_hexa_pos_one_A_2_2.c \
					test_float_hexa/100_test_float_hexa_pos_two_A_2_2.c \
					test_float_hexa/101_test_float_hexa_neg_A_2_2.c \
					test_float_hexa/102_test_float_hexa_inf_one_A_2_2.c \
					test_float_hexa/103_test_float_hexa_inf_zero_one_A_2_2.c \
					test_float_hexa/104_test_float_hexa_den_A_2_2.c \
					test_float_hexa/105_test_float_hexa_round_even_top_A_2_2.c \
					test_float_hexa/106_test_float_hexa_round_even_down_A_2_2.c \
					test_float_hexa/107_test_float_hexa_round_even_top_neg_A_2_2.c \
					test_float_hexa/108_test_float_hexa_round_even_down_neg_A_2_2.c \
					test_float_hexa/109_test_float_hexa_null_A_3_3.c \
					test_float_hexa/110_test_float_hexa_null_neg_A_3_3.c \
					test_float_hexa/111_test_float_hexa_pos_one_A_3_3.c \
					test_float_hexa/112_test_float_hexa_pos_two_A_3_3.c \
					test_float_hexa/113_test_float_hexa_neg_A_3_3.c \
					test_float_hexa/114_test_float_hexa_inf_one_A_3_3.c \
					test_float_hexa/115_test_float_hexa_inf_zero_one_A_3_3.c \
					test_float_hexa/116_test_float_hexa_den_A_3_3.c \
					test_float_hexa/117_test_float_hexa_round_even_top_A_3_3.c \
					test_float_hexa/118_test_float_hexa_round_even_down_A_3_3.c \
					test_float_hexa/119_test_float_hexa_round_even_top_neg_A_3_3.c \
					test_float_hexa/120_test_float_hexa_round_even_down_neg_A_3_3.c \
					test_float_hexa/121_test_float_hexa_null_A_4_4.c \
					test_float_hexa/122_test_float_hexa_null_neg_A_4_4.c \
					test_float_hexa/123_test_float_hexa_pos_one_A_4_4.c \
					test_float_hexa/124_test_float_hexa_pos_two_A_4_4.c \
					test_float_hexa/125_test_float_hexa_neg_A_4_4.c \
					test_float_hexa/126_test_float_hexa_inf_one_A_4_4.c \
					test_float_hexa/127_test_float_hexa_inf_zero_one_A_4_4.c \
					test_float_hexa/128_test_float_hexa_den_A_4_4.c \
					test_float_hexa/129_test_float_hexa_round_even_top_A_4_4.c \
					test_float_hexa/130_test_float_hexa_round_even_down_A_4_4.c \
					test_float_hexa/131_test_float_hexa_round_even_top_neg_A_4_4.c \
					test_float_hexa/132_test_float_hexa_round_even_down_neg_A_4_4.c \
					test_float_hexa/133_test_float_hexa_null_A_5_5.c \
					test_float_hexa/134_test_float_hexa_null_neg_A_5_5.c \
					test_float_hexa/135_test_float_hexa_pos_one_A_5_5.c \
					test_float_hexa/136_test_float_hexa_pos_two_A_5_5.c \
					test_float_hexa/137_test_float_hexa_neg_A_5_5.c \
					test_float_hexa/138_test_float_hexa_inf_one_A_5_5.c \
					test_float_hexa/139_test_float_hexa_inf_zero_one_A_5_5.c \
					test_float_hexa/140_test_float_hexa_den_A_5_5.c \
					test_float_hexa/141_test_float_hexa_round_even_top_A_5_5.c \
					test_float_hexa/142_test_float_hexa_round_even_down_A_5_5.c \
					test_float_hexa/143_test_float_hexa_round_even_top_neg_A_5_5.c \
					test_float_hexa/144_test_float_hexa_round_even_down_neg_A_5_5.c
